### PR TITLE
Update Tests to respect Mocha changes in beforeEach

### PR DESCRIPTION
**Pull request by AlexDobeck**
Fixed tests broken in recent version updates.

Sorry about the naming, couldn't quite think of anything better.

Resolution dealt with changes in Mocha's beforeEach function being run on every child causing the doIt function to recurse on itself. Also updated examples to match new Restify formatter.

### CODE REVIEW

**Comment by AlexDobeck** [comment]
I don't believe the Travic CI build will succeed still.

The npm test script stumbles on the 'vows' execution since it doesn't appear to terminate.

Have validated that each individual integration script runs fine, but not sure what the solution would be other than pulling them out or waiting for vows to fix.

**Comment by jocull** [comment]
+1

**Comment by AlexDobeck** [comment]
Looks like it might be related to the example servers not being terminated?

Possible Dirty hack:
setTimeout(server.close,1000)

**Comment by AlexDobeck** [comment]
Haha, so thought up a solution that's probably as good as I'm going manage.

So best guess source of this integration-tests-never-terminating issue is vows 0.8.x which had an issue where servers are not automatically drained and closed where they previously were https://github.com/vowsjs/vows/issues/341. 

With api-easy not being updated in over a year, the other solution would be to possibly downgrade back to api-easy v0.3.8, or rewrite the integration tests to use native vows.

**Pull request merged**
