### PR TITLE
[WIP] Adding refresh_token to ROPC

### PR DESCRIPTION
**Pull request by tomgco**
This is currently a work in progress of adding refresh tokens to the ROPC flow. 

I thought I would open this now so I could start a discussion / get some feedback on this as I haven't worked with the oauth spec for long, and hopefully I have followed it correctly.

It should be in working order with tests passing, as well as being backwards compatible, missing things that I am aware of are: 
### Things Missing
- [ ] New tests covering this additional (optional) implementation
- [ ] Updated Documentation
- [ ] Updated Example

### CODE REVIEW

**Comment by gmaniac** [comment]
+1 Has anything else been done on this?

**Comment by kazimierasc** [comment]
+1
Yeah, the ability to use refresh tokens would be very helpful.

**Comment by domenic** [comment]
I'm sorry but I no longer have time to maintain this package. If you're interested, let me know and I'll give you npm publish rights and you can switch to publishing from your fork.

**Comment by gmaniac** [comment]
I am interested, gmaniac is my username on npm as well.

**Comment by domenic** [comment]
@gmaniac you should be added! All yours :).

**Comment by gmaniac** [comment]
I updated thanks!

**Comment by remotevision** [comment]
curious if this one was merged?

**Comment by gmaniac** [comment]
Sorry for the delay, been real busy. I will pull this down this weekend and give it a test. I am not sure though this is how we are wanting to do this. I will let you know after this weekend either way.

Open to discussion though, have you already tested this? Or are you just looking to use refresh_token?

**Pull request closed without merging**
